gallery/urls.py
from django.urls import path
from gallery.views import IndexView, AstrophotographyView, AstrophotographySearchView, AstrophotographyRegisterView


app_name = 'gallery'
urlpatterns =[
    path('', IndexView.as_view(), name='index'),
    path('object/<int:pk>/', AstrophotographyView.as_view(), name='astrophotography'),
    path('buscar-imagem', AstrophotographySearchView.as_view(), name='search'),
    path('image-register/', AstrophotographyRegisterView.as_view(), name='astro_register')

]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("gallery.urls")),
    path("users/",include("users.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Rotas dos arquivos de mídias(imagens)

users/urls.py
from django.urls import path
from users.views import UserRegister, LoginView, LogoutView, UserUpdateView


app_name = 'users'
urlpatterns =[
    path('register', UserRegister.as_view(), name='user_register'),
    path('login', LoginView.as_view(), name='login'),
    path('logout',LogoutView.as_view(), name='logout'),
    path('update/<int:pk>', UserUpdateView.as_view(), name='update')
]

templates/partials/_footer.html
{% load static %}

<footer class="rodape">
    <div class="rodape__icones">
        <a href="https://twitter.com/AluraOnline" target=”_blank” >
            <img src="{% static '/assets/ícones/1x/twitter.png' %}" alt="ícone twitter">
        </a>
        <a href="https://www.instagram.com/aluraonline/" target=”_blank” >
            <img src="{% static '/assets/ícones/1x/instagram.png' %}" alt="ícone instagram">
        </a>
    </div>
    <p class="rodape__texto">Desenvolvido por Alura</p>
</footer>

templates/partials/_menu.html
{% load static %}

<section class="menu-lateral">
    <nav class="menu-lateral__navegacao">
        <a href="{% url 'gallery:index' %}"><img src="{% static '/assets/ícones/1x/Home - ativo.png' %}"> Home</a>
        <a href="#"><img src="{% static '/assets/ícones/1x/Mais vistas - inativo.png' %}"> Mais vistas</a>

        {% if user.is_authenticated %}
            {% if user.is_superuser %}
            <a href="{% url 'admin:index' %}"><img src="{% static '/assets/ícones/1x/Home - ativo.png' %}"> Admin</a>
            {% endif %}
        <a href="#"><img src="{% static '/assets/ícones/1x/Surpreenda-me - ativo.png' %}"> Minhas imagens</a>
        <a href="{% url 'gallery:astro_register' %}"><img src="{% static '/assets/ícones/1x/Novas - inativo.png' %}"> Nova imagem</a>
        <a href="{% url 'users:logout' %}"><img src="{% static '/assets/ícones/1x/Surpreenda-me - inativo.png' %}"> Logout</a>
        {% else %} 
        <a href="{% url 'users:login' %}"><img src="{% static '/assets/ícones/1x/Mais vistas - inativo.png' %}"> Login</a>
        <a href="{% url 'users:user_register' %}"><img src="{% static '/assets/ícones/1x/Novas - inativo.png' %}"> Cadastrar</a>
        {% endif %}
            
    </nav>
</section>