gallery/urls.py
from django.urls import path
from gallery.views import IndexView, AstrophotographyView, AstrophotographySearchView, AstrophotographyRegisterView


app_name = 'gallery'
urlpatterns =[
    path('', IndexView.as_view(), name='index'),
    path('object/<int:pk>/', AstrophotographyView.as_view(), name='astrophotography'),
    path('buscar-imagem', AstrophotographySearchView.as_view(), name='search'),
    path('image-register/', AstrophotographyRegisterView.as_view(), name='astro_register')

]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("gallery.urls")),
    path("users/",include("users.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Rotas dos arquivos de mídias(imagens)

gallery/models/AstronomicalObject.py
from django.db import models


class AstronomicalObject(models.Model):
    categories = (
        ('Galáxia', 'Galáxia'),
        ('Aglomerado', 'Aglomerado'),
        ('Estrela', 'Estrela'),
        ('Nebulosa', 'Nebulosa'),
        ('Planeta', 'Planeta'),
        ('Outros','Outros'),
    )

    title = models.CharField('Título', max_length=500)
    image_source = models.CharField('Fonte', max_length=50, default='')
    date_image = models.DateField('Data da Imagem', default='2000-01-01')
    description = models.TextField('Descrição')
    image = models.ImageField('Foto', upload_to='pictures/%Y/%m/%d', blank=True)
    category = models.CharField('Categoria', choices=categories, max_length=20, default='Outros')
    published = models.BooleanField('Publicado', default=False)

    def __str__(self) -> str:
        return self.title

gallery/models/Astrophotography.py
from django.db import models
from django.contrib.auth.models import User


class Astrophotography(models.Model):
    categories = (
        ('Galáxia', 'Galáxia'),
        ('Aglomerado', 'Aglomerado'),
        ('Estrela', 'Estrela'),
        ('Nebulosa', 'Nebulosa'),
        ('Planeta', 'Planeta'),
    )
    image = models.ImageField('Foto', upload_to='pictures/%Y/%m/%d', blank=True)
    image_source = models.CharField('Fonte', max_length=50, default='')
    title = models.CharField('Título', max_length=500)
    date_image = models.DateField('Data da Imagem', default='2000-01-01')
    description = models.TextField('Descrição')
    category = models.CharField('Categoria', choices=categories, max_length=20, default='Outros')
    published = models.BooleanField('Publicado', default=False)
    registered_by = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self) -> str:
        return self.title

gallery/models/ObjectAstronomic.py
from django.db import models


class ObjectAstronomic(models.Model):
    title = models.CharField('Título', max_length=500)
    description = models.TextField('Descrição')
    image = models.ImageField('Foto', upload_to='pictures/%Y/%m/%d', blank=True)

gallery/forms/AstrophotographyRegisterForm.py
from django import forms
from gallery.models import Astrophotography


class AstrophotographyRegisterForm(forms.ModelForm):
    class Meta:
        model = Astrophotography
        exclude = ['published', 'registered_by']

        widgets = {
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control'
                }
            ),

            'image_source': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),

            'title': forms.TextInput(
                attrs={
                    'class':'form-control'
                }
            ),

            'date_image': forms.DateInput(
                attrs={
                    'type':'date',
                    'class':'form-control'
                }
            ),

            'description': forms.Textarea(
                attrs={
                    'class': 'form-control'
                }
            ),

            'category': forms.Select(
                attrs={
                    'class':'form-control'
                }
            ),
        
        }

    def clean(self):
        return super().clean()

gallery/views/AstronomicalObjectView.py
from django.views.generic.detail import DetailView
from gallery.models import AstronomicalObject


class AstronomicalObjectView(DetailView):
    template_name = 'gallery/imagem.html'
    model = AstronomicalObject

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

gallery/views/AstrophotographyRegisterView.py
from django.views.generic.edit import FormView
from gallery.forms import AstrophotographyRegisterForm
from django.shortcuts import redirect
from django.contrib.auth.models import User


class AstrophotographyRegisterView(FormView):
    form_class = AstrophotographyRegisterForm
    template_name = 'gallery/astrophotagray_register.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def post(self, request, *args, **kwargs):
        user = User.objects.get(id=request.user.id)
        form = AstrophotographyRegisterForm(self.request.POST, self.request.FILES)

        if form.is_valid():
            astro_image = form.save(commit=False)
            astro_image.published = True
            astro_image.registered_by = user
            astro_image.save()

        return redirect('gallery:index')

gallery/views/AstrophotographySearchView.py
from django.views.generic import TemplateView
from gallery.models import Astrophotography


class AstrophotographySearchView(TemplateView):
    template_name = 'gallery/index.html'

    def post(self, request, **kwargs):
        context = super().get_context_data(**kwargs)
        keyword = request.POST['search']
        objects = Astrophotography.objects.filter(title__icontains=keyword)
        context['objects'] = objects
        return self.render_to_response(context)

gallery/views/AstrophotographyView.py
from django.views.generic.detail import DetailView
from gallery.models import Astrophotography


class AstrophotographyView(DetailView):
    template_name = 'gallery/imagem.html'
    model = Astrophotography

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

gallery/views/AtronomicalObjectSearchView.py
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.http import HttpResponse
from gallery.models import AstronomicalObject


class AtronomicalObjectSearchView(TemplateView):
    template_name = 'gallery/index.html'

    def post(self, request, **kwargs):
        context = super().get_context_data(**kwargs)
        keyword = request.POST['search']
        objects = AstronomicalObject.objects.filter(title__icontains=keyword)
        context['objects'] = objects
        return self.render_to_response(context)

gallery/views/IndexView.py
from django.views.generic.base import TemplateView
from gallery.models import Astrophotography


class IndexView(TemplateView):
    template_name = 'gallery/index.html'

    def get_context_data(self, **kwargs):
        
        context = super().get_context_data(**kwargs)
        context['objects'] = Astrophotography.objects.filter(published=True)
        
        return context

gallery/views/ObjectAtronomicView.py
from django.views.generic.base import TemplateView


class ObjectAtronomicView(TemplateView):
    template_name = 'gallery/imagem.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

templates/gallery/astrophotagray_register.html
{% extends 'template_base.html' %}
{% block content %} 

<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
</head>

<section class="galeria" style="margin-left: 5em">
    <form action="{% url 'gallery:astro_register' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            {% for field in form.visible_fields %}
            <div class="col-12 col-lg-12" style="margin-bottom: 10px;">
                <label for="{{ field.id_for_label }}" style="color:#D9D9D9; margin-bottom: 5px;">{{field.label}}</label>
                {{ field }}
            </div>
            {% for error in field.errors %}
            <div class="alert alert-danger" style=" height: 70%;">
                {{error}}
            </div>
            {% endfor %}
            {% endfor %}            
        </div>
        <div>
            <button type="submit" class="btn btn-success col-12" style="padding: top 5px;">Cadastrar</button>
        </div>
    </form>
</section>

{% endblock %}

templates/gallery/imagem.html
{% extends 'template_base.html' %}
{% load static %}

{% block content %} 

<section class="conteudo">
    <section class="imagem">
        <div class="imagem__conteudo">
            <img class="imagem__imagem" src="{{ object.image.url }}">
            <div class="imagem__info">
                <div class="imagem__texto">
                    <p class="imagem__titulo">{{ object.title }} - {{ object.image_source }}</p>
                    <p class="imagem__descricao">{{ object.date_image }}</p>
                    <p class="imagem__texto">{{ object.description }}</p>
                </div>
            </div>
        </div>
    </section>
</section>

{% endblock %}

templates/gallery/index.html
{% extends 'template_base.html' %} 
{% load static %}

{% block content %}

<section class="conteudo">
    <section class="banner">
        <img class="banner__imagem" src="{% static '/assets/imagens/Banner(2).png' %}" alt="banner Alura Space">
        <h1 class="banner__titulo"> A galeria mais completa de fotos do espaço!</h1>
    </section>
    <section class="tags">
        <p class="tags__titulo">Busque por tags:</p>
        <ul class="tags__lista">
            <li class="tags__tag">Nebulosa</li>
            <li class="tags__tag">Estrela</li>
            <li class="tags__tag">Galáxia</li>
            <li class="tags__tag">Planeta</li>
        </ul>
    </section>
    <section class="galeria">
        <div class="cards">

            {% if objects %}

                <h2 class="cards__titulo">Navegue pela galeria</h2>
                <ul class="cards__lista">

                    {% for object in objects %}

                        <li class="card">
                            <a href="{% url 'gallery:astrophotography' object.id %}">
                                <img class="card__imagem" src="{{ object.image.url }}"
                                    alt="foto">
                            </a>
                            <span class="card__tag">{{ object.category }}</span>
                            <div class="card__info">
                                <p class="card__titulo">{{ object.title }}</p>
                                <div class="card__texto">
                                    <p class="card__descricao">{{ object.image_source }}</p>
                                    <span>
                                        <img src="{% static '/assets/ícones/1x/favorite_outline.png' %}" alt="ícone de coração">
                                    </span>
                                </div>
                            </div>
                        </li>
                    
                    {% endfor %}

                </ul>

            {% endif %}

        </div>
    </section>
</section>

{% endblock %}