gallery/urls.py
from django.urls import path
from gallery.views import IndexView, AstrophotographyView, AstrophotographySearchView, AstrophotographyRegisterView


app_name = 'gallery'
urlpatterns =[
    path('', IndexView.as_view(), name='index'),
    path('object/<int:pk>/', AstrophotographyView.as_view(), name='astrophotography'),
    path('buscar-imagem', AstrophotographySearchView.as_view(), name='search'),
    path('image-register/', AstrophotographyRegisterView.as_view(), name='astro_register')

]

setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("gallery.urls")),
    path("users/",include("users.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # Rotas dos arquivos de mídias(imagens)

templates/template_base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Alura Space</title>
    <link rel="shortcut icon" href="{% static '/assets/favicon/Favicon 64px 2.png' %}" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static '/styles/style.css' %}">

</head>

<body>

    <div class="pagina-inicial">
        <header class="cabecalho">
            <img src="{% static '/assets/logo/Logo(2).png' %}" alt="Logo da Alura Space" />
            <div class="cabecalho__busca">
                <div class="busca__fundo">
                    <form action="{% url 'gallery:search' %}" class="form-search" method="post">{% csrf_token %}
                        <input class="busca__input" name="search"type="text" placeholder="O que você procura?">
                        <button class="btn-search" type="submit">
                            <img class="busca__icone" src="{% static '/assets/ícones/1x/search.png' %}"
                                alt="ícone de search">
                        </button>
                    </form>
                </div>
            </div>
        </header>
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{message.tags}}" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        <h1 class="title-page">{{ title_page }}</h1>
        <main class="principal">


            {% include 'partials/_menu.html' %}

            {% block content %}

            {% endblock %}


        </main>
    </div>

    {% include 'partials/_footer.html' %}
</body>

</html>